#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/yc-el

# Written by Jim Van Zandt <jrv@vanzandt.mv.com>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=yc-el

unset XEMACS

if [ ${FLAVOR} = emacs ]; then exit 0; fi

#
## checking MULE supported XEmacs. (for XEmacs/MULE is needed elisp)
# 2006-Feb-08 We have only XEmacs21 in Debian stable and unstable.
#
if [ ${FLAVOR} = xemacs21 ]; then
        XEMACS=`ls /usr/bin/xemacs*21*-mule* 2> /dev/null | head -1`
        if [ -z ${XEMACS} ]; then
                echo
                echo "install/${PACKAGE}: Ignoring ${FLAVOR}."
                echo "${PACKAGE} needs MULE supported XEmacs."
                exit 0;
        fi
        XEMACS=`basename ${XEMACS}`
fi

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

SITEFLAG=-no-site-file
FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}

# 2005.12.15 : yabuki;  We have emacs21 in Sarge. 
# I think that yc-el package does not need to check emacs19 are installing

# Install-info-altdir does not actually exist. 
# Maybe somebody will write it.
if test -x /usr/sbin/install-info-altdir; then
    echo install/${PACKAGE}: install Info links for ${FLAVOR}
    install-info-altdir --quiet --section "" "" --dirname=${FLAVOR} /usr/info/${PACKAGE}.info.gz
fi

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
FILES=`echo *.el`
rm -f ${ELCDIR}/*.el
cp ${FILES} ${ELCDIR}
cd ${ELCDIR}

cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
EOF
# 2006-Feb-07 yabuki
if [ -z ${XEMACS} ]; then
  # Do byte compile with emacs21 or ...
  echo " ${FLAVOR} ${FLAGS} ${FILES}"
  ${FLAVOR} ${FLAGS} ${FILES}
else
  #you are xemacs21 byte compile(only xemacs with mule feature)
  echo "${XEMACS} ${FLAGS} ${FILES}"
  ${XEMACS} ${FLAGS} ${FILES}
fi
rm -f *.el path.el
#
ln -fs ${ELDIR}/yc.el ${ELCDIR}/

exit 0
